#! /bin/sh

. "${HOME}/.cache/wal/colors.sh"

## AUTOSTART
sxhkd &

${HOME}/.config/polybar/launch.sh
nm-applet &
fcitx -d &
dunst &
numlockx &
jetbrains-toolbox --minimize &
birdtray &
picom -b &
redshift-gtk &
wal -a "90" -i "${HOME}/Pictures/Wallpapers" -o "${HOME}/.scripts/theme/dunstwal.sh" &
pulseeffects --gapplication-service &
automathemely &
/opt/urserver/urserver --daemon &
xsettingsd &

## CONFIG
bspc config border_width 20
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

## RULES
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

## DISPLAY SETUP
bspc monitor DVI-I-1 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

xcalib -o DVI-D-0 /usr/share/color/icc/BenQ\ RL2455HM\ ICC\ Profile\ \(Standard\ Mode\).icm &
xcalib -o DVI-I-1 /usr/share/color/icc/BenQ\ XL2411Z\ 144Hz.icm &
xcalib -o HDMI-0 /usr/share/color/icc/lent2424za.icm &