#!/usr/bin/env bash
#
# set-dark - set dark GTK theme using xsettingsd
#
# requires: xsettingsd
#
# this script is primarily intended to be used with automathemely

set -o errexit
set -o nounset

readonly XSETTINGSD_DIR="$HOME/.config/xsettingsd"

main() {
  xsettingsd -c "${XSETTINGSD_DIR}/dark" &
}
main